SELECT
 LOOKUP_ID
, HOUSEHOLD_NAME
, FIRST_NAME
, EMAIL_ADDRESS AS 'Email Address'
, SOLICIT_CODE1 AS SOLICIT_CODE
, DECEASED
, 0 AS ACCEPTS_EMAIL
, SFMC_DONOR_ATTRIBUTE
FROM 
[BrightVineSolutions_Deceased] dne
