SELECT
CASE WHEN new.[Member ID] IS NOT NULL THEN new.[Member ID]
ELSE new.EmailAddress END AS SUBSCRIBER_KEY
, new.FirstName AS FIRST_NAME
, new.LastName AS LAST_NAME
, new.EmailAddress AS EMAIL_ADDRESS
, new.ZipCode AS ZIP
, new.[Member ID] AS LOOKUP_ID
, new.SFMC_SUB_KEY
FROM [MW - All Warmup Seg] new
LEFT JOIN  [test0401013928438] cons
ON new.EmailAddress = cons.EMAIL_ADDRESS
WHERE SUBSCRIBER_KEY IS NULL


SELECT DISTINCT
CASE WHEN new.LOOKUP_ID IS NOT NULL THEN new.LOOKUP_ID
ELSE new.EmailAddress END AS SUBSCRIBER_KEY
, new.FirstName AS FIRST_NAME
, new.LastName AS LAST_NAME
, new.EmailAddress AS EMAIL_ADDRESS
, new.ZipCode AS ZIP
, new.LOOKUP_ID AS LOOKUP_ID
, new.SFMC_SUB_KEY
FROM [MW - April Combined] new
LEFT JOIN  [test0401013928438] cons
ON new.EmailAddress = cons.EMAIL_ADDRESS
WHERE SUBSCRIBER_KEY IS NULL




SELECT
CASE WHEN new.LOOKUP_ID IS NOT NULL THEN new.LOOKUP_ID
ELSE new.EmailAddress END AS SUBSCRIBER_KEY
, new.FirstName AS FIRST_NAME
, new.LastName AS LAST_NAME
, new.EmailAddress AS EMAIL_ADDRESS
, new.ZipCode AS ZIP
, new.STATE AS STATE
, new.LOOKUP_ID AS LOOKUP_ID
, new.SFMC_SUB_KEY
, new.ORIGIN_SRC_CODE
, new.LO_CONS_ID
FROM [MW-Co-Op-April2023 - Batch1-4] new
LEFT JOIN  [test0401013928438] cons
ON new.EmailAddress = cons.EMAIL_ADDRESS




SELECT
CASE WHEN new.LOOKUP_ID IS NOT NULL THEN new.LOOKUP_ID 
ELSE new.EMAIL_ADDRESS END AS SUBSCRIBER_KEY
, new.FIRST_NAME
, new.HOUSEHOLD_NAME
, new.ZIP
, new.LOOKUP_ID
, new.LO_CONS_ID
, new.SFMC_SUB_KEY
, new.STATE
, new.ADDRESS_COUNTRY
, new.ORIGIN_SRC_CODE
,'3/2/2023  2:50:00 PM' AS ORIGIN_DATE
FROM [MW - Co-Op - March 2023 - Batch 1] new
LEFT JOIN  [test0401013928438] cons
ON new.EMAIL_ADDRESS = cons.EMAIL_ADDRESS




SELECT
CASE WHEN new.LOOKUP_ID IS NOT NULL THEN new.LOOKUP_ID
ELSE new.EmailAddress END AS SUBSCRIBER_KEY
, new.FirstName AS FIRST_NAME
, new.LastName AS LAST_NAME
, new.EmailAddress AS EMAIL_ADDRESS
, new.ZipCode AS ZIP
, new.STATE AS STATE
, new.LOOKUP_ID AS LOOKUP_ID
, new.SFMC_SUB_KEY
, COALESCE (ORIGIN_DATE, '4/10/2023 2:50:00 PM') AS ORIGIN_DATE
, CASE WHEN cons.ORIGIN_SRC_CODE IS NULL THEN new.ORIGIN_SRC_CODE
       ELSE cons.ORIGIN_SRC_CODE
  END AS ORIGIN_SRC_CODE
, new.LO_CONS_ID
FROM [MW-Co-Op-April2023 - Batch1-4] new
LEFT JOIN  [test0401013928438] cons
ON new.EmailAddress = cons.EMAIL_ADDRESS




SELECT
CASE WHEN new.LOOKUP_ID IS NOT NULL THEN new.LOOKUP_ID
ELSE new.EmailAddress END AS SUBSCRIBER_KEY
, new.FirstName AS FIRST_NAME
, new.LastName AS LAST_NAME
, new.EmailAddress AS EMAIL_ADDRESS
, new.ZipCode AS ZIP
, new.STATE AS STATE
, new.LOOKUP_ID AS LOOKUP_ID
, new.SFMC_SUB_KEY
, COALESCE (ORIGIN_DATE, '6/2/2023 2:50:00 PM') AS ORIGIN_DATE
, CASE WHEN cons.ORIGIN_SRC_CODE IS NULL THEN new.ORIGIN_SRC_CODE
       ELSE cons.ORIGIN_SRC_CODE
  END AS ORIGIN_SRC_CODE
, new.LO_CONS_ID
FROM [MW - Co-Op - Reactivation - June 2023 - Batch 1] new
LEFT JOIN  [test0401013928438] cons
ON new.EmailAddress = cons.EMAIL_ADDRESS

