


SELECT SUBSCRIBER_KEY
, IMPORT_DATE
, WebForm
, Luminate
, AdvantageAI
, ConstantContact
, BBCRM
, CONSTITUENT_TYPE
, ALTERNATE_LOOKUP_ID
, ALTERNATE_LOOKUP_ID_TYPE_CODE
, LOOKUP_ID
, SFMC_SUB_KEY
, EMAIL_ADDRESS
, FIRST_NAME
, MIDDLE_NAME
, HOUSEHOLD_NAME
, TITLE
, SUFFIX
, ADDRESS_TYPE
, ADDRESS_COUNTRY
, ADDRESS
, CITY
, STATE
, ZIP
, ADDRESS_INFO_SOURCE
, EMAIL_STATUS
, DO_NOT_EMAIL
, OPT_IN_DATE
, DATE_CHANGED
, ACCEPTS_EMAIL
, ACCEPTS_SMS
, ACCEPTS_PHONE
, EMAIL_ADDRESS_PRIMARY
, EMAIL_ADDRESS_TYPE
, EMAIL_ADDRESS_INFO_SOURCE
, SOLICIT_CODE1
, SOLICIT_CODE1_START_DATE
, SOLICIT_CODE1_END_DATE
, ORIGIN_SRC_CODE
, ORIGIN_SUB_CODE
, HH_FIRST_GIFT_DATE
, HH_MOST_RECENT_GIFT_DATE
, HH_LARGEST_LIFETIME_GIFT_DATE
, DEVELOPMENT_PORTFOLIO_TAG_ATTRIBUTE
, PROSPECT_MANAGER
, DECEASED
, HH_FIRST_GIFT_AMOUNT
, HH_MOST_RECENT_GIFT_AMOUNT
, HH_LARGEST_LIFETIME_GIFT_AMOUNT
, BIRTH_DATE
, GENDER
, COMPANY
, DEPARTMENT
, PHONE
, PHONE_ALT
, SFMC_DONOR_ATTRIBUTE
, ORIGIN_DATE
FROM [BBCRM AND NON-CRM SFMC - Direct Response] 
WHERE  AdvantageAI = 'TRUE'











SELECT dr.SUBSCRIBER_KEY
, dr.IMPORT_DATE
, dr.WebForm
, dr.Luminate
, dr.AdvantageAI
, dr.ConstantContact
, dr.BBCRM
, dr.CONSTITUENT_TYPE
, dr.ALTERNATE_LOOKUP_ID
, dr.ALTERNATE_LOOKUP_ID_TYPE_CODE
, dr.LOOKUP_ID
, dr.SFMC_SUB_KEY
, dr.EMAIL_ADDRESS
, dr.FIRST_NAME
, dr.MIDDLE_NAME
, dr.HOUSEHOLD_NAME
, dr.TITLE
, dr.SUFFIX
, dr.ADDRESS_TYPE
, dr.ADDRESS_COUNTRY
, dr.ADDRESS
, dr.CITY
, dr.STATE
, dr.ZIP
, dr.ADDRESS_INFO_SOURCE
, dr.EMAIL_STATUS
, dr.DO_NOT_EMAIL
, dr.OPT_IN_DATE
, dr.DATE_CHANGED
, dr.ACCEPTS_EMAIL
, dr.ACCEPTS_SMS
, dr.ACCEPTS_PHONE
, dr.EMAIL_ADDRESS_PRIMARY
, dr.EMAIL_ADDRESS_TYPE
, dr.EMAIL_ADDRESS_INFO_SOURCE
, dr.SOLICIT_CODE1
, dr.SOLICIT_CODE1_START_DATE
, dr.SOLICIT_CODE1_END_DATE
, COALESCE (dblo.ORIGIN_SRC_CODE, dbmw.ORIGIN_SRC_CODE, adv.ORIGIN_SRC_CODE, dr.ORIGIN_SRC_CODE, '') AS ORIGIN_SRC_CODE
, dr.ORIGIN_SUB_CODE
, dr.HH_FIRST_GIFT_DATE
, dr.HH_MOST_RECENT_GIFT_DATE
, dr.HH_LARGEST_LIFETIME_GIFT_DATE
, dr.DEVELOPMENT_PORTFOLIO_TAG_ATTRIBUTE
, dr.PROSPECT_MANAGER
, dr.DECEASED
, dr.HH_FIRST_GIFT_AMOUNT
, dr.HH_MOST_RECENT_GIFT_AMOUNT
, dr.HH_LARGEST_LIFETIME_GIFT_AMOUNT
, dr.BIRTH_DATE
, dr.GENDER
, dr.COMPANY
, dr.DEPARTMENT
, dr.PHONE
, dr.PHONE_ALT
, dr.SFMC_DONOR_ATTRIBUTE
, COALESCE (dblo.ORIGIN_DATE, dbmw.ORIGIN_DATE, adv.ORIGIN_DATE, dr.ORIGIN_DATE, dr.IMPORT_DATE, '') AS ORIGIN_DATE
, COALESCE (dr.GROUP_ID, adv.GROUP_ID, dr.ORIGIN_SRC_CODE, adv.ORIGIN_SRC_CODE, dbmw.ORIGIN_SRC_CODE, dblo.ORIGIN_SRC_CODE, '') AS GROUP_ID
FROM [BBCRM AND NON-CRM SFMC - Direct Response] dr
LEFT JOIN [REF Luminate Origin Date and Src] dblo ON dr.SUBSCRIBER_KEY = dblo.SUBSCRIBER_KEY
LEFT JOIN [REF Past MW Origin Segmentations] dbmw ON dr.SUBSCRIBER_KEY = dbmw.SUBSCRIBER_KEY
LEFT JOIN [AdvantageAI Housefile_Test1] adv ON dr.SUBSCRIBER_KEY = adv.SUBSCRIBER_KEY